//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFNutritionFitnessManagement1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int Id { get; set; }
        public string MajorCategory { get; set; }
        public string GeneralCategory { get; set; }
        public string SpecificActivity { get; set; }
        public Nullable<decimal> MET { get; set; }
    }
}
